# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H3jHceDH5Q_OHk1x0sM4nwSu_KWmTbXs
"""

import pandas as pd
import altair as alt

file_url = 'https://raw.githubusercontent.com/PacktWorkshops/The-Data-Science-Workshop/master/Chapter10/dataset/churn.csv'

df = pd.read_csv(file_url)

df.shape

df.dtypes

df.head()

df.tail()

df.sample(n=5, random_state=8)

df.describe()

for col_name in ['churn', 'internationalplan', 'voicemailplan']:
  print(f"{col_name}: {df[col_name].unique()}")

chart1 = alt.Chart(df).mark_bar().encode(
    alt.X("churn"),
    y='count()'
)

chart2 = alt.Chart(df).mark_bar().encode(
    alt.X("internationalplan"),
    y='count()'
)

chart3 = alt.Chart(df).mark_bar().encode(
    alt.X("voicemailplan"),
    y='count()'
)

chart1 | chart2 | chart3

num_df = df.select_dtypes(include='number')

num_cols = num_df.columns
num_cols.values

charts = alt.Chart(df).mark_bar().encode(
    alt.X(alt.repeat("column"), type='quantitative', bin=True),
    y='count()'
)

charts.repeat(
    column=list(num_cols)
)

alt.Chart(df).mark_boxplot().encode(
    x='churn',
    y='totaldaycalls'
)

alt.Chart(df).mark_boxplot().encode(
    x='churn',
    y='numbervmailmessages'
)

